apiVersion: v1
kind: Pod
metadata:
  name: jenkins-build
  labels:
    some-label: pod
spec:
  containers:
    - name: linter
      image: wideblue/test-linting-tools
      command:
        - cat
      tty: true
    - name: docker
      image: docker:19.03
      command:
        - cat
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
    - name: kubectl
      image: lachlanevenson/k8s-kubectl:v1.15.12  
      command:
        - cat
      tty: true
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
