master:
    useSecurity: true
    adminUser: adminUser
    adminPassword: adminPassword
    numExecutors: 1
    installPlugins:
      - kubernetes:1.25.7
      - workflow-job:2.39
      - workflow-aggregator:2.6
      - credentials-binding:1.20
      - git:3.12.1
      - command-launcher:1.4
      - github-branch-source:2.7.1
      - docker-workflow:1.23
      - pipeline-utility-steps:2.3.1
      - blueocean:1.23.2
    overwritePlugins: true
    serviceType: LoadBalancer
    # ingress:
    #   enabled: true
    #   hostName: localhost
    #   path: /jenkins/.*
    #   annotations:
    #     kubernetes.io/ingress.class: gloo
  