Description: >
  Damjan Dvoršek / Deploys the EKS control plane.
  
Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Type: String
  EKSClusterName:
    Type: String
    Description: Name of  EKS Cluster.    
  EKSClusterRoleName:
    Type: String
    Description: Name of IAM role for the EKS service.  
       

Resources:  
  EKSClusterProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref EKSClusterRole  
  EKSClusterRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
          Principal:
            Service:
              - eks.amazonaws.com
          Action:
            - 'sts:AssumeRole'
      RoleName: !Ref EKSClusterRoleName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess


  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication with worker nodes
      VpcId: 
        Fn::ImportValue: !Sub ${EnvironmentName}-VPC  
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref EKSClusterName
      RoleArn: !GetAtt EKSClusterRole.Arn
        ResourcesVpcConfig:
          SecurityGroupIds:
          - !Ref ControlPlaneSecurityGroup
          SubnetIds:
          - Fn::ImportValue: !Sub ${EnvironmentName}-PublicSubnet0
          - Fn::ImportValue: !Sub ${EnvironmentName}-PublicSubnet1
          - Fn::ImportValue: !Sub ${EnvironmentName}-WebSubnet0
          - Fn::ImportValue: !Sub ${EnvironmentName}-WebSubnet1


Outputs:
  ControlPlaneSecurityGroup:
    Description: A reference to ControlPlaneSecurityGroup
    Value: !Ref ControlPlaneSecurityGroup
    Export:
      Name: !Sub ${EnvironmentName}-ControlPlaneSecurityGroup
  EKSClusterName:
    Description: A reference to the EKS cluster name.
    Value: !Ref EKSClusterName
    Export:
      Name: !Sub ${EnvironmentName}-EKSClusterName          
