- hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/main.yaml

  tasks:
    - name: CloudFormation create VPC.
      cloudformation:
        stack_name: eks-simple-vpc
        state: present
        region: "{{ aws_region }}"
        profile: "{{ aws_profile }}"
        disable_rollback: true
        template: VPC/templates/aws-simple-vpc.yaml
        tags:
          stack: eks-simple-vpc
          application: eks-simple
      register: vpc_info
    
    - name: Add to stack_outputs.
      set_fact:
        stack_outputs: "{{ stack_outputs | combine(vpc_info['stack_outputs']) }}"    

    - debug:
        msg: "{{ stack_outputs }}"

    - name: "Running eksctl cluster create with name {{ eks_cluster_name }}."
      command: "eksctl create cluster --vpc-public-subnets={{ stack_outputs.SubnetIds }} -n {{ eks_cluster_name }} -t {{ eks_nodegroup_instance_type }} -M {{ eks_nodegroup_cluster_size }} -r {{ aws_region }}"
      register: eksctl
    - debug: msg={{ eksctl }}

    - name: "Create jenkins namespace"
      command: "kubectl apply -f Jenkins/manifests/jenkins-namespace.yaml "
 
    - name: Install Jenkins to cluster with helm chart.
      command: "helm install jenkins stable/jenkins --values Jenkins/jenkins-values.yaml -n jenkins"
      register: helm_jenkins
    - debug: msg={{ helm_jenkins }}